export const GET_ALL_PLAN_REQUEST="GET_ALL_PLAN_REQUEST"
export const GET_ALL_PLAN_SUCCESS="GET_ALL_PLAN_SUCCESS"
export const GET_ALL_PLAN_FAILURE="GET_ALL_PLAN_FAILURE"

export const ADD_PLAN_REQUEST="ADD_PLAN_REQUEST"
export const ADD_PLAN_SUCCESS="ADD_PLAN_SUCCESS"
export const ADD_PLAN_FAILURE="ADD_PLAN_FAILURE"

export const DELETE_PLAN_REQUEST="DELETE_PLAN_REQUEST"
export const DELETE_PLAN_SUCCESS="DELETE_PLAN_SUCCESS"
export const DELETE_PLAN_FAILURE="DELETE_PLAN_FAILURE"

export const UPDATE_PLAN_REQUEST="UPDATE_PLAN_REQUEST"
export const UPDATE_PLAN_SUCCESS="UPDATE_PLAN_SUCCESS"
export const UPDATE_PLAN_FAILURE="UPDATE_PLAN_FAILURE"

export const GET_ALL_VIDEO_REQUEST="GET_ALL_VIDEO_REQUEST"
export const GET_ALL_VIDEO_SUCCESS="GET_ALL_VIDEO_SUCCESS"
export const GET_ALL_VIDEO_FAILURE="GET_ALL_VIDEO_FAILURE"

export const ADD_VIDEO_REQUEST="ADD_VIDEO_REQUEST"
export const ADD_VIDEO_SUCCESS="ADD_VIDEO_SUCCESS"
export const ADD_VIDEO_FAILURE="ADD_VIDEO_FAILURE"

export const DELETE_VIDEO_REQUEST="DELETE_VIDEO_REQUEST"
export const DELETE_VIDEO_SUCCESS="DELETE_VIDEO_SUCCESS"
export const DELETE_VIDEO_FAILURE="DELETE_VIDEO_FAILURE"

export const UPDATE_VIDEO_REQUEST="UPDATE_VIDEO_REQUEST"
export const UPDATE_VIDEO_SUCCESS="UPDATE_VIDEO_SUCCESS"
export const UPDATE_VIDEO_FAILURE="UPDATE_VIDEO_FAILURE"