export const GET_ALL_PLAN_REQUEST="GET_ALL_PLAN_REQUEST"
export const GET_ALL_PLAN_SUCCESS="GET_ALL_PLAN_SUCCESS"
export const GET_ALL_PLAN_FAILURE="GET_ALL_PLAN_FAILURE"

export const GET_ALL_VIDEO_REQUEST="GET_ALL_VIDEO_REQUEST"
export const GET_ALL_VIDEO_SUCCESS="GET_ALL_VIDEO_SUCCESS"
export const GET_ALL_VIDEO_FAILURE="GET_ALL_VIDEO_FAILURE"

export const GET_MY_PLAN_REQUEST="GET_MY_PLAN_REQUEST"
export const GET_MY_PLAN_SUCCESS="GET_MY_PLAN_SUCCESS"
export const GET_MY_PLAN_FAILURE="GET_MY_PLAN_FAILURE"

export const BUY_PLAN_REQUEST="BUY_PLAN_REQUEST"
export const BUY_PLAN_SUCCESS="BUY_PLAN_SUCCESS"
export const BUY_PLAN_FAILURE="BUY_PLAN_FAILURE"

export const DELETE_MY_PLAN_REQUEST="DELETE_MY_PLAN_REQUEST"
export const DELETE_MY_PLAN_SUCCESS="DELETE_MY_PLAN_SUCCESS"
export const DELETE_MY_PLAN_FAILURE="DELETE_MY_PLAN_FAILURE"